version: '3.8'

services:
  stagehand-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stagehand-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - HOST=${HOST}
      - PORT=${PORT}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - STEEL_API_KEY=${STEEL_API_KEY}
    volumes:
      # Mount downloads directory để lưu file tải về
      - ./downloads:/app/downloads
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - stagehand-network
    # Security options
    security_opt:
      - no-new-privileges:true
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  stagehand-network:
    driver: bridge

volumes:
  downloads:
  logs: 